[package]
name = "railreader2"
version = "0.1.0"
edition = "2021"

[dependencies]
vello = "0.6"
winit = "0.30"
lopdf = "0.34"
pollster = "0.4"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
skrifa = "0.37"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
